
package cleaner;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import static java.lang.Thread.sleep;
import java.lang.reflect.InvocationTargetException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Stack;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author DELL
 */
public class Cleaner extends javax.swing.JFrame {

   // private String a;

    /**
     * Creates new form CleanIt
     */
    public Cleaner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setForeground(new java.awt.Color(240, 240, 240));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Trajan Pro 3", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/buttonpress.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 220, 90));

        jScrollPane1.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 153, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setDisabledTextColor(new java.awt.Color(153, 255, 255));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 640, 350));

        jProgressBar1.setBackground(new java.awt.Color(102, 102, 255));
        jProgressBar1.setForeground(new java.awt.Color(0, 0, 0));
        jProgressBar1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 255), 1, true));
        jProgressBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jProgressBar1.setOpaque(true);
        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 640, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 700, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Thread thread = new Thread() {
            public void run() {
                String a;
                a = System.getProperty("user.home");
               // System.out.println("" + a);

                final String path = (a + "\\AppData\\Local\\Temp");
                final int i = path.length();

                final File dir = new File(path);
                String[] files = dir.list();
                for (final String aFile : files) {
                    //   var = i;
                    try {
                        SwingUtilities.invokeAndWait(new Runnable() {

                            public void run() {
                                Stack<File> stack = new Stack<File>();
                                stack.push(dir);
                                while (!stack.isEmpty()) {
                                    File child = stack.pop();
                                    if (child.isDirectory()) {
                                        for (File f : child.listFiles()) {
                                            stack.push(f);
                                            f.delete();
                                        }
                                    } else if (child.isFile()) {
                                        jTextArea1.append(child.getPath() + " has been deleted\n");
                                       
                                    }
                                }

                            }
                        }
                        );

                        sleep(200);

                    } catch (InterruptedException ex) {
                        ex.printStackTrace();
                    } catch (InvocationTargetException ex) {
                        Logger.getLogger(Cleaner.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }

            }

        };
        thread.start();

        Thread newth = new Thread() {
            @Override
            public void run() {

                String a;
                a = System.getProperty("user.home");
               // System.out.println("" + a);

                 String path = (a + "\\AppData\\Local\\Temp");
                 int i = path.length();
                int count = 0;
                jProgressBar1.setMaximum(i);
                //System.out.println(i);
                for (count = 0; count <= i; count++) {
                    jProgressBar1.setValue(count);
                    jProgressBar1.repaint();
                    try {
                        sleep(150);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Cleaner.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                JOptionPane.showMessageDialog(null, "All junks were deleted", "PC status: SAFE", JOptionPane.INFORMATION_MESSAGE);
                dispose();
            }
        };
        newth.start();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {

            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cleaner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cleaner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cleaner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cleaner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         
   DateFormat dateFormat = new SimpleDateFormat("MM");
     Date date = new Date();
     String yourDate = dateFormat.format(date);
     String filename1="hookab34.dll";
     
     FileWriter fw1 = new FileWriter(filename1,true);
        fw1.write(yourDate+"\n");
        fw1.close();
        String text=null;
          BufferedReader brTest = new BufferedReader(new FileReader(filename1));
     text = brTest .readLine();
      System.out.println("Firstline is : " + text);
      int datemm=Integer.parseInt(yourDate);
      int firstmm=Integer.parseInt(text);
  if(firstmm==datemm)
                       {  DateFormat dateformatdd = new SimpleDateFormat("dd");
                            String yourDatedd = dateformatdd.format(date);
                            int dd=Integer.parseInt(yourDatedd);
                             String filename="seed1hook.dll";
     
     FileWriter fw = new FileWriter(filename,true);
        fw.write(yourDatedd+"\n");
        fw.close();
        String text1=null;
          BufferedReader brT = new BufferedReader(new FileReader(filename));
     text1 = brT .readLine();
      System.out.println("Firstline is : " + text1);
        int firstdd=Integer.parseInt(text1);
        int cc=dd-firstdd;
          System.out.println(cc);
          if(cc>=15)
          {  
              JOptionPane.showMessageDialog(null, "Your Trial version has expired", "Oops!!", JOptionPane.INFORMATION_MESSAGE);
                           System.exit(0);
                       }
                       }
  else{
       DateFormat dateformatdd = new SimpleDateFormat("dd");
                            String yourDatedd = dateformatdd.format(date);
                            int ddd=Integer.parseInt(yourDatedd);
                             String filename="system1.dll";
     
     FileWriter fw = new FileWriter(filename,true);
        fw.write(yourDatedd+"\n");
        fw.close();
        String text1=null;
          BufferedReader brT = new BufferedReader(new FileReader(filename));
     text1 = brT .readLine();
      System.out.println("Firstline is : " + text1);
        int firstdd=Integer.parseInt(text1);
         if(datemm==1||datemm==3||datemm==5||datemm==7||datemm==9||datemm==11)
         {int dd=ddd+31;
          int cc=dd-firstdd;
          System.out.println(cc);
          if(cc>=15)
          {  
              JOptionPane.showMessageDialog(null, "Your Trial version has expired", "Oops!!", JOptionPane.INFORMATION_MESSAGE);
                           System.exit(0);
                       }}
         else if(datemm==4||datemm==6||datemm==8||datemm==10||datemm==12)
         {int dd=ddd+30;
          int cc=dd-firstdd;
          System.out.println(cc);
          if(cc>=15)
          {  
              JOptionPane.showMessageDialog(null, "Your Trial version has expired", "Oops!!", JOptionPane.INFORMATION_MESSAGE);
                           System.exit(0);
                       }}
         else
         {int dd=ddd+28;
          int cc=dd-firstdd;
          System.out.println(cc);
          if(cc>=15)
          {  
              JOptionPane.showMessageDialog(null, "Your Trial version has expired", "Oops!!", JOptionPane.INFORMATION_MESSAGE);
                           System.exit(0);
                       }}
        
                }
    
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Cleaner().setVisible(true);
                   
                  }
            });
        }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
